# Generated by Django 4.1.7 on 2023-03-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122, unique=True)),
                ('password', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('image', models.ImageField(upload_to='profile_image')),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('image', models.FileField(upload_to='profile_image')),
                ('pincode', models.CharField(max_length=6)),
                ('company_name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=122)),
                ('discountPercentage', models.CharField(max_length=122)),
                ('rating', models.CharField(max_length=122)),
                ('stock', models.CharField(max_length=122)),
                ('brand', models.CharField(max_length=122)),
                ('category', models.CharField(max_length=122)),
                ('thumbnali', models.FileField(upload_to='product_image')),
                ('images', models.FileField(upload_to='product_image')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivary_address', models.TextField()),
                ('order_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Delivary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excepted_delivary_date', models.DateField()),
                ('delivary_status', models.TextField()),
                ('delivaried_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
